CREATE TABLE users (
  username VARCHAR_IGNORECASE(50) NOT NULL PRIMARY KEY,
  password VARCHAR_IGNORECASE(50) NOT NULL,
  enabled  BOOLEAN                NOT NULL
);

CREATE TABLE authorities (
  username  VARCHAR_IGNORECASE(50) NOT NULL,
  authority VARCHAR_IGNORECASE(50) NOT NULL,
  CONSTRAINT fk_authorities_users FOREIGN KEY (username) REFERENCES users (username)
);
CREATE UNIQUE INDEX ix_auth_username ON authorities (username, authority);

CREATE TABLE Translation (
  id             BIGINT generated BY DEFAULT AS IDENTITY,
  finalLanguage  VARCHAR(255),
  inputText      VARCHAR(255),
  sourceLanguage VARCHAR(255),
  PRIMARY KEY (id)
)